<html>
<head>
<META http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>
     CIP JavaScript documentation for class "
	pfcShrinkwrapFacetedPartInstructions"
    </title>
<link href="cipdoc_default.css" type="text/css" rel="stylesheet">
<script language="JAVASCRIPT">
  function findProperNode ()
  {  
   
     top.frames [0].document.apiwizard.api (
      2,
      484
     ); 
    
  } 
 </script>
</head>
<body onLoad="findProperNode()" class="frame-entity">
<table cellspacing="0" width="100%" border="0" class="toolbar">
<tr>
<td class="toolbar-navigation"><a href="library.html">Library</a>&nbsp;|&nbsp;<a href="m-pfcShrinkwrap.html">Module</a></td><td class="toolbar-lib-name">
  
 </td>
</tr>
</table>
<hr>
<h2>Class&nbsp;pfcShrinkwrapFacetedPartInstructions</h2>
<hr>
<br>
<b>Description</b>
<br>
<br>This interface contains instructions to export a solid model to a shrinkwrap faceted part.
<br>
<dl>
<dt>
<b>See Also:</b>
</dt>
<dd>
<tt><b><a class="method" href="t-pfcSolid-Solid.html#ExportShrinkwrap">pfcSolid.ExportShrinkwrap()</a></b></tt>
</dd>
</dl>
<dl>
<dt>
<b>Direct Parent Classes:</b>
</dt>
<dd>
<a class="class" href="t-pfcShrinkwrap-ShrinkwrapFacetedFormatInstructions.html">pfcShrinkwrapFacetedFormatInstructions</a>
</dd>
</dl>
<br>
<hr>
<br>
<b>Property Summary</b>
<br>
<br>
<table cellpadding="3" border="0" class="method-summary">
<tr>
<td></td>
</tr>
<tr>
<td class="return-type"><tt>boolean</tt></td><td class="func-signature"><tt><a class="method" href="#Lightweight">Lightweight</a></tt></td>
</tr>
<tr>
<td></td><td colspan="2" class="entities-text"><tt>true</tt> if the output part should be lightweight, <tt>null</tt> or <tt>false</tt> otherwise.</td>
</tr>
<tr>
<td></td>
</tr>
<tr>
<td class="return-type"><tt><a class="type" href="t-pfcModel-Model.html">pfcModel</a></tt></td><td class="func-signature"><tt><a class="method" href="#OutputModel">OutputModel</a></tt></td>
</tr>
<tr>
<td></td><td colspan="2" class="entities-text">The solid model handle where the geometry will be created. You can create an empty part through <tt><b><a class="method" href="t-pfcSession-BaseSession.html#CreatePart">pfcBaseSession.CreatePart()</a></b></tt> or copy a template model using <tt><b><a class="method" href="t-pfcModel-Model.html#Copy">pfcModel.Copy()</a></b></tt>.</td>
</tr>
<tr>
<td></td>
</tr>
</table>
<br>
<hr>
<br>
<b>Method Summary</b>
<br>
<br>
<table cellpadding="3" border="0" class="method-summary">
<tr>
<td></td>
</tr>
<tr>
<td class="return-type"><tt>static&nbsp;<a class="type" href="t-pfcShrinkwrap-ShrinkwrapFacetedPartInstructions.html">pfcShrinkwrapFacetedPartInstructions</a></tt></td><td class="func-signature"><tt><a class="method" href="#Create">Create</a>
 (<a class="type" href="t-pfcModel-Model.html">pfcModel</a>&nbsp;OutputModel, boolean&nbsp;Lightweight)
</tt></td>
</tr>
<tr>
<td></td><td colspan="2" class="entities-text">Creates a new instructions object used to export a faceted shrinkwrap model.
</td>
</tr>
<tr>
<td></td>
</tr>
</table>
<br>
<hr>
<br>
<b>Property Detail</b>
<br>
<hr>
<br>
<a name="Lightweight">
<table cellpadding="5" cellspacing="0" border="0" class="method-def">
<tr>
<td class="return-type"><tt>boolean</tt></td><td class="func-name"><tt>Lightweight</tt></td>
</tr>
</table>
</a>
<table border="0" class="method-doc">
<tr>
<td></td><td>
<br>
<tt>true</tt> if the output part should be lightweight, <tt>null</tt> or <tt>false</tt> otherwise.<br>
<dl>
<dt>
<b>Manual References:</b>
</dt>
<dd>
<a href="../manual0/Jinterface.html#109">Interface: Faceted Solid Options</a>
</dd>
</dl>
<br>
</td>
</tr>
</table>
<br>
<hr>
<br>
<a name="OutputModel">
<table cellpadding="5" cellspacing="0" border="0" class="method-def">
<tr>
<td class="return-type"><tt><a class="type" href="t-pfcModel-Model.html">pfcModel</a></tt></td><td class="func-name"><tt>OutputModel</tt></td>
</tr>
</table>
</a>
<table border="0" class="method-doc">
<tr>
<td></td><td>
<br>The solid model handle where the geometry will be created. You can create an empty part through <tt><b><a class="method" href="t-pfcSession-BaseSession.html#CreatePart">pfcBaseSession.CreatePart()</a></b></tt> or copy a template model using <tt><b><a class="method" href="t-pfcModel-Model.html#Copy">pfcModel.Copy()</a></b></tt>.<br>
<br>
</td>
</tr>
</table>
<br>
<br>
<hr>
<br>
<b>Method Detail</b>
<br>
<hr>
<br>
<a name="Create">
<table cellpadding="5" cellspacing="0" border="0" class="method-def">
<tr>
<td class="return-type"><tt>static&nbsp;<a class="type" href="t-pfcShrinkwrap-ShrinkwrapFacetedPartInstructions.html">pfcShrinkwrapFacetedPartInstructions</a></tt></td><td class="func-name"><tt>Create</tt></td><td class="func-params"><tt>
 (<a class="type" href="t-pfcModel-Model.html">pfcModel</a>&nbsp;OutputModel, boolean&nbsp;Lightweight)
</tt></td>
</tr>
</table>
</a>
<table border="0" class="method-doc">
<tr>
<td></td><td>
<br>Creates a new instructions object used to export a faceted shrinkwrap model.
<br>
<dl>
<dt>
<b>See Also:</b>
</dt>
<dd>
<tt><b><a class="method" href="t-pfcSolid-Solid.html#ExportShrinkwrap">pfcSolid.ExportShrinkwrap()</a></b></tt>
</dd>
</dl>
<dl>
<dt>
<b>Manual References:</b>
</dt>
<dd>
<a href="../manual0/Jinterface.html#108">Interface: Faceted Solid Options</a>, <a href="../manual0/Jinterface.html#109">Interface: Faceted Solid Options</a>
</dd>
</dl>
<dl>
<dt>
<b>Parameters:</b>
</dt>
<dd>
<dl>
<dt>
<tt><b>OutputModel</b></tt>
</dt>
<dd>The output model where geometry will be created.  Use <tt><b><a class="method" href="t-pfcSession-BaseSession.html#CreatePart">pfcBaseSession.CreatePart()</a></b></tt> to obtain an empty part, or copy a template with <tt><b><a class="method" href="t-pfcModel-Model.html#Copy">pfcModel.Copy()</a></b></tt>.</dd>
<dt>
<tt><b>Lightweight</b></tt>
</dt>
<dd>
<tt>true</tt> to create a lightweight shrinkwrap part, <tt>null</tt> or <tt>false</tt> to create a normal shrinkwrap part.</dd>
</dl>
</dd>
</dl>
<dl>
<dt>
<b>Returns:</b>
</dt>
<dd>The created instructions object.</dd>
</dl>
</td>
</tr>
</table>
<br>
</body>
</html>
